#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR=$(CDPATH="" cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH="" cd -- "${SCRIPT_DIR}/.." && pwd)
. "${ROOT_DIR}/lib/common"

SAVES_DIR="${ROOT_DIR}/backups"

copy_dir() {
  local src_dir
  src_dir="$1"

  repo_name="$(basename "${src_dir}")"
  suffix="$(date +"%Y%m%d-%H%M%S")"
  dst_dir="${SAVES_DIR}/${repo_name}-${suffix}"

  echo -n "${dst_dir}"
}

make_copy() {
  local src_dir dst_dir
  src_dir="$1"
  dst_dir="$2"
  shift 2

  src_dir="$(realpath "${src_dir}")"
  if has_flag "--on-copied" "$@"; then
    info "Making copy repo ${src_dir} to ${dst_dir}"
    mkdir -p "${SAVES_DIR}"
    cp -r "${src_dir}" "${dst_dir}"
  elif has_flag "--on-cloned" "$@"; then
    info "Cloning repo ${src_dir} to ${dst_dir}"
    mkdir -p "${SAVES_DIR}"
    git clone --mirror "${src_dir}" "${dst_dir}"
  else
    info "No copy made"
  fi
}
