#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
ROOT_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
. "${ROOT_DIR}/lib/common"

REPO_DIR="${REPO_DIR:?REPO_DIR is not set}"

print_help() {
  local cmd="${CMD:-}"
  [[ -z "${cmd}" ]] && cmd="$0"

  cat <<EOF
Usage:
  ${cmd} <glob_pattern>...

Description:
  Drop all files matching glob patterns.

Arguments:
  <glob_pattern>    List of glob patterns.

Environment:
  REPO_DIR          (required) Path to the target repository.

Examples:
  REPO_DIR="\$(pwd)" ${cmd} .env
  REPO_DIR="\$(pwd)" ${cmd} '*.a' '*.o'
EOF
}

main() {
  has_flag "--help" "$@" && print_help && exit 0

  test "$#" -lt 1 &&  die "No glob patterns passed."

  for arg in "$@"; do
    info "Applying glob ${arg}"
    GIT filter-repo --invert-paths --path-glob "${arg}"
  done
}

main "$@"
