#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
ROOT_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
. "${ROOT_DIR}/lib/common"

REPO_DIR="${REPO_DIR:?REPO_DIR is not set}"

print_help() {
  local cmd="${CMD:-}"
  [[ -z "${cmd}" ]] && cmd="$0"

  cat <<EOF
Usage:
  ${cmd} <search> <replacement> [-i] [-w]

Description:
  Perform a search-and-replace on historical file paths across the full history.

Arguments:
  <search>          Regexp pattern to replace in file paths.
  <replacement>     Replacement text.

Options:
  -i                Ignore case.
  -w                Match the search term as a whole word (word-regex).
  --help            Show this help message and exit.

Environment:
  REPO_DIR          (required) Path to the target repository.

Examples:
  REPO_DIR="\$(pwd)" ${cmd} 'subdir/project/' 'project/'
  REPO_DIR="\$(pwd) "${cmd} 'tmp' 'temp' -i -w
  REPO_DIR="\$(pwd) "${cmd} 'secrets/([a-z]+)\.env' '\\\\1.env'
EOF
}

main() {
  has_flag "--help" "$@" && print_help && exit 0

  local search="$1"
  local replace="$2"
  local ignore_case=
  local word_regexp=

  shift 2
  has_flag "-i" "$@" && ignore_case="--ignore-case"
  has_flag "-w" "$@" && word_regexp="--word-regexp"

  local python_flags=
  local python_search="${search}"
  [[ -n "${ignore_case}" ]] && python_flags="flags=re.IGNORECASE"
  [[ -n "${word_regexp}" ]] && python_search="\\b${python_search}\\b"

# | sed '/^[^"]/s/.*/"&"/' \
  local python_filepaths
  python_filepaths="$(GIT --no-pager log --all --name-only --pretty= \
    | sed -E 's/^"(.+)"$/\1/' \
    | sort \
    | uniq \
    | grep -E --color=never ${ignore_case} ${word_regexp} "${search}" \
    | sed -E 's/^(.+)$/"\1",/' \
    | paste -sd' ' - || true
  )"

  [[ -z "${python_filepaths}" ]] && die "Nothing to rewrite."

  local python_code
  python_code="$(cat <<EOF
import re, sys
filepaths = { ${python_filepaths} }
decoded = filename.decode('utf-8', 'surrogateescape')
${if:-if} decoded not in filepaths:
    return filename

return re.sub(r"${python_search}", "${replace}", decoded, ${python_flags}).encode('utf-8', 'surrogateescape')
EOF
)"

  GIT filter-repo --force --filename-callback "${python_code}"
}

main "$@"
