#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
ROOT_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
. "${ROOT_DIR}/lib/common"

REPO_DIR="${REPO_DIR:?REPO_DIR is not set}"

print_help() {
  local cmd="${CMD:-}"
  [[ -z "${cmd}" ]] && cmd="$0"

  cat <<EOF
Usage:
  ${cmd}

Description:
  Rewrite all commit timestamps to UTC (preserving relative order).

Options:
  --help            Show this help message and exit.

Environment:
  REPO_DIR          (required) Path to the target repository.

Examples:
  REPO_DIR="\$(pwd)" ${cmd}
EOF
}

main() {
  has_flag "--help" "$@" && print_help && exit 0

  local repo_dir
  repo_dir="$1"; shift
  repo_dir=$(realpath "${repo_dir}")
  is_git_repo "${repo_dir}" || die "'${repo_dir}' is not a git repository"

  local python_code
  python_code="$(cat <<EOF
    timestamp_str, _ = commit.author_date.split()
    commit.author_date = timestamp_str + b" +0000"
    timestamp_str, _ = commit.committer_date.split()
    commit.committer_date = timestamp_str + b" +0000"
EOF
)"

  info "Making changes of repo: ${repo_dir}"

  GIT filter-repo --force --commit-callback "${python_code}"

  info "Check the result ${repo_dir}"
}

main "$@"
