#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR=$(CDPATH="" cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH="" cd -- "${SCRIPT_DIR}/.." && pwd)
. "${ROOT_DIR}/lib/common"

search_in_filepaths() {
  local text="$1"
  local ignore_case=

  has_flag "-i" "$@" && ignore_case="--ignore-case"

  git -C "${REPO_DIR}" log --all --name-only --pretty= | grep --color=always -E ${ignore_case} "${text}"
}