#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR=$(CDPATH="" cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH="" cd -- "${SCRIPT_DIR}/.." && pwd)
. "${ROOT_DIR}/lib/common"

GIT() {
  git -C "${REPO_DIR}" "$@"
}

search_in_filepaths() {
  local search="$1"
  local ignore_case=
  local word_regexp=

  has_flag "-i" "$@" && ignore_case="--ignore-case"
  has_flag "-w" "$@" && word_regexp="--word-regexp"

  GIT --no-pager log --all --name-only --pretty= \
  | sort \
  | uniq \
  | grep --color=always ${ignore_case} ${word_regexp} "${search}" || true
}
