#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR=$(CDPATH="" cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH="" cd -- "${SCRIPT_DIR}/.." && pwd)
. "${ROOT_DIR}/lib/common"

GIT() {
  git -C "${REPO_DIR}" "$@"
}

grep_filepaths() {
  local search="$1"
  shift 1
  local grep_flags="$@"

  GIT --no-pager log --all --name-only --pretty= \
  | sort \
  | uniq \
  | grep ${grep_flags} "${search}" || true
}

search_in_filepaths() {
  local search="$1"
  local ignore_case=
  local word_regexp=

  has_flag "-i" "$@" && ignore_case="--ignore-case"
  has_flag "-w" "$@" && word_regexp="--word-regexp"

  grep_filepaths "${search}" ${ignore_case} ${word_regexp} --color=always

  # Calculate stats
  local total_found=0
  total_found="$(grep_filepaths "${search}" ${ignore_case} ${word_regexp} | wc -l | awk '{print $1}')"
  echo "Total found: "${total_found}
}
