#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR=$(CDPATH="" cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH="" cd -- "${SCRIPT_DIR}/.." && pwd)
. "${ROOT_DIR}/lib/common"
. "${ROOT_DIR}/lib/copy"

DEFAULT_HEAD="${DEFAULT_HEAD:-refs/heads/main}"

GIT() {
  git -C "${REPO_DIR}" "$@"
}

commit_tree() {
  local signing_key="$1"
  local sha="$2"
  local parent_sha="$3"

  local parent=
  [[ -n "${parent_sha}" ]] && parent="-p ${parent_sha}"

  local format author_name author_email author_date committer_name committer_email committer_date message
  format="%an%x00%ae%x00%aD%x00%cn%x00%ce%x00%cD%x00%B%x00%T%x00"
  exec 3< <(GIT rev-list -1 --format="${format}" "${sha}" | sed '1d')
  IFS= read -r -d '' author_name <&3
  IFS= read -r -d '' author_email <&3
  IFS= read -r -d '' author_date <&3
  IFS= read -r -d '' committer_name <&3
  IFS= read -r -d '' committer_email <&3
  IFS= read -r -d '' committer_date <&3
  IFS= read -r -d '' message <&3
  IFS= read -r -d '' tree_sha <&3
  exec 3<&-

  local commit_sha
  commit_sha="$(
    GIT_AUTHOR_NAME="${author_name}" \
    GIT_AUTHOR_EMAIL="${author_email}" \
    GIT_AUTHOR_DATE="${author_date}" \
    GIT_COMMITTER_NAME="${committer_name}" \
    GIT_COMMITTER_EMAIL="${committer_email}" \
    GIT_COMMITTER_DATE="${committer_date}" \
    GIT commit-tree -S"${signing_key}" -m "${message}" ${parent} "${tree_sha}"
  )"

  echo "${commit_sha}"
}

sign_commits() {
  if [[ $(GIT rev-list --min-parents=2 "${DEFAULT_HEAD}" | wc -l) -ne 0 ]]; then
    die "History is not linear."
  fi

  local signing_key
  signing_key="$(GIT config user.signingkey || true)"
  [[ -z "${signing_key}" ]] && die "No signing key set in repository."

  local current_branch
  current_branch="$(GIT symbolic-ref HEAD)"

  local parent_sha=
  while read -r sha; do
    parent_sha="$(commit_tree "${signing_key}" "${sha}" "${parent_sha}")"
  done < <(GIT rev-list --reverse --all)

  GIT update-ref "${current_branch}" "${parent_sha}"
}
